/// Flutter icons Lotura
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Lotura
///      fonts:
///       - asset: fonts/Lotura.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Lotura {
  Lotura._();

  static const _kFontFam = 'Lotura';
  static const String? _kFontPkg = null;

  static const IconData list = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laundry = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dry = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData working = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkCircle = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disconnected = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancelCircle = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triangleUp = IconData(0xf311, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
